#!/usr/bin/env python

import time

import rospy
from gazebo_msgs.msg import ModelState
from gazebo_msgs.srv import SetModelState

if __name__ == "__main__":
    rospy.init_node('simulator')

    state_msg = ModelState()
    state_msg.model_name = 'turtlebot3_waffle'
    state_msg.pose.position.x = 5.0
    state_msg.pose.position.y = -2.0
    state_msg.pose.position.z = 0.0

    state_msg.pose.orientation.x = 0.0
    state_msg.pose.orientation.y = 0.0
    state_msg.pose.orientation.z = 0.0
    state_msg.pose.orientation.w = 0.0

    set_model_state = rospy.ServiceProxy('/gazebo/set_model_state', SetModelState)
    resp = set_model_state(state_msg)

    time.sleep(5.0)
