name: Build

on:
  push:
    branches:
      - master
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: convert repository name to lowercase
        run: |
          echo "IMAGE_REPOSITORY=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: build & publish docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_REPOSITORY }}:latest
            ghcr.io/${{ env.IMAGE_REPOSITORY }}:${{ github.sha }}
